version: '2'
services:
  gitwebhook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./data/app:/data
    ports:
      - "10080:80"
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:3
    volumes:
      - ./data/redis:/data
